CREATE DATABASE IF NOT EXISTS test;
DROP TABLE IF EXISTS city;
CREATE TABLE city(id INT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(50),province VARCHAR(50),country VARCHAR(30));
INSERT city VALUES(DEFAULT,"深圳","广东","中国");
INSERT city VALUES(DEFAULT,"杭州","浙江","中国");