#服务器配置
server:
 port: 80

#数据库配置
jdbc:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    maxActive: 2335
    maxIdel: 120
    maxWait: 100


